name:                alertdiff
version:             0.1.0.0
github:              "weaveworks/alertdiff"
license:             ALv2
author:              "Adam Harrison"
maintainer:          "awh@weave.works"
copyright:           "2018 Weaveworks"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/alertdiff#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - async
  - bytestring
  - containers
  - http-client
  - optparse-applicative
  - split
  - servant-client
  - servant-server
  - stm
  - transformers

executables:
  alertdiff:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alertdiff
    - containers
    - http-client
    - http-client-tls
    - optparse-applicative
    - servant-client
    - stm
    - warp

tests:
  alertdiff-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alertdiff
